[package]
name = "rink"
version = "0.1.0"
authors = ["Andrew <healeycodes@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
unicode-segmentation = "1.7.1"